name       : fceux
version    : 2.6.5
release    : 12
source     :
    - https://github.com/TASEmulators/fceux/archive/refs/tags/v2.6.5.tar.gz : 78156f3685c55849351178773940871ed607bc4fc37f233fdab58c232e3208fa
license    : GPL-2.0-later
component  : games.emulator
summary    : NES/Famicom Emulator
description: |
    FCEUX is a Nintendo Entertainment System (NES), Famicom, Famicom Disk System (FDS), and Dendy emulator. It supports PAL (European), NTSC (USA/JPN), and Hybrid (PAL) modes.
builddeps  :
    - pkgconfig(lua-5.1)
    - pkgconfig(minizip)
    - pkgconfig(opengl)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(sdl2)
setup      : |
    %patch -p1 < $pkgfiles/0001-Allow-defaults-for-native-file-dialog-and-native-men.patch
    sed -i 's*//#define PUBLIC_RELEASE*#define PUBLIC_RELEASE*' src/version.h
    %cmake_ninja -DGLVND=true \
                 -DUSE_NATIVE_FILE_DIALOG=true \
                 -DUSE_NATIVE_MENU_BAR=true \
                 -DQT6=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Make fceux work with icon themes
    mv $installdir/usr/share/pixmaps/fceux1.png $installdir/usr/share/pixmaps/fceux.png
    install -Dm00644 $pkgfiles/org.TasEmulators.fceux.desktop $installdir/usr/share/applications/org.TasEmulators.fceux.desktop
    rm -v $installdir/usr/share/applications/fceux.desktop
