name       : fceux
version    : 2.5.0
release    : 6
source     :
    - https://downloads.sourceforge.net/project/fceultra/Source%20Code/2.5.0%20src/fceux-2.5.0.tar.gz : 65d84a3cc5814ad958b8a06b835c1660c8320bd66cb34ef33c147d6374cd1b20
license    : GPL-2.0-later
component  : games.emulator
summary    : NES/Famicom Emulator
description: |
    FCEUX is a Nintendo Entertainment System (NES), Famicom, Famicom Disk System (FDS), and Dendy emulator. It supports PAL (European), NTSC (USA/JPN), and Hybrid (PAL) modes.
builddeps  :
    - pkgconfig(lua-5.1)
    - pkgconfig(minizip)
    - pkgconfig(opengl)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(sdl2)
setup      : |
    %patch -p1 < $pkgfiles/0001-Allow-defaults-for-native-file-dialog-and-native-men.patch
    sed -i 's*//#define PUBLIC_RELEASE*#define PUBLIC_RELEASE*' src/version.h
    %cmake_ninja -DGLVND=true -DUSE_NATIVE_FILE_DIALOG=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Make fceux work with icon themes
    mv $installdir/usr/share/pixmaps/fceux1.png $installdir/usr/share/pixmaps/fceux.png
    install -Dm00644 $pkgfiles/fceux.desktop $installdir/usr/share/applications/fceux.desktop
