name       : fceux
version    : 2.2.3
release    : 3
source     :
    - http://downloads.sourceforge.net/project/fceultra/Source%20Code/2.2.3%20src/fceux-2.2.3.src.tar.gz : 4be6dda9a347f941809a3c4a90d21815b502384adfdd596adaa7b2daf088823e
license    : GPL-2.0-later
component  : games.emulator
summary    : NES/Famicom Emulator
description: |
    FCEUX is a Nintendo Entertainment System (NES), Famicom, Famicom Disk System (FDS), and Dendy emulator. It supports PAL (European), NTSC (USA/JPN), and Hybrid (PAL) modes.
builddeps  :
    - scons
    - pkgconfig(sdl)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lua-5.1)
    - pkgconfig(gdlib)
    - pkgconfig(glu)
setup      : |
    %apply_patches
build      : |
    scons
install    : |
    scons --prefix=$installdir/usr install
